"""
This type stub file was generated by pyright.
"""

from . import core, motor_gridfs

"""Tornado support for Motor, an asynchronous driver for MongoDB."""
def create_motor_class(cls): # -> Type[_]:
    ...

MotorClient = create_motor_class(core.AgnosticClient)
MotorClientSession = create_motor_class(core.AgnosticClientSession)
MotorDatabase = create_motor_class(core.AgnosticDatabase)
MotorCollection = create_motor_class(core.AgnosticCollection)
MotorCursor = create_motor_class(core.AgnosticCursor)
MotorCommandCursor = create_motor_class(core.AgnosticCommandCursor)
MotorLatentCommandCursor = create_motor_class(core.AgnosticLatentCommandCursor)
MotorChangeStream = create_motor_class(core.AgnosticChangeStream)
MotorGridFSBucket = create_motor_class(motor_gridfs.AgnosticGridFSBucket)
MotorGridIn = create_motor_class(motor_gridfs.AgnosticGridIn)
MotorGridOut = create_motor_class(motor_gridfs.AgnosticGridOut)
MotorGridOutCursor = create_motor_class(motor_gridfs.AgnosticGridOutCursor)
MotorClientEncryption = create_motor_class(core.AgnosticClientEncryption)
