image: python:3.9.5-alpine

services:
  - mongo:latest

stages:
  # - setup
  # - test
  - publish

# install:
#   stage: setup
#   script:
#     - pip install poetry

# test:
#   stage: test
#   script:
#     - poetry run task test

publish-package:
  stage: publish
  script:
    - apk add --no-cache libffi-dev openssl-dev curl
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
    # - tee export PATH="/root/.local/bin:$PATH"
    # - pip install poetry
    # - poetry install
    # - poetry version patch
    - /root/.local/bin/poetry config repositories.gitlab https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi
    - /root/.local/bin/poetry config http-basic.gitlab gitlab-ci-token ${CI_JOB_TOKEN}
    - /root/.local/bin/poetry build
    - /root/.local/bin/poetry publish -r gitlab

  only:
    - master
