version: "3.1"
services:
  mongodb:
    image: mongo:latest
    container_name: overlead-odm-mongodb
    ports:
      - 0:27017
    volumes:
      - .mongodb:/data/db

networks:
  default:
    name: overlead-odm
