"""
This type stub file was generated by pyright.
"""

from typing import TypeVar

from . import core
from . import motor_gridfs

T = TypeVar('T')


def create_asyncio_class(cls: T) -> T:
    ...


AsyncIOMotorClient = create_asyncio_class(core.AgnosticClient)
AsyncIOMotorClientSession = create_asyncio_class(core.AgnosticClientSession)
AsyncIOMotorDatabase = create_asyncio_class(core.AgnosticDatabase)
AsyncIOMotorCollection = create_asyncio_class(core.AgnosticCollection)
AsyncIOMotorCursor = create_asyncio_class(core.AgnosticCursor)
AsyncIOMotorCommandCursor = create_asyncio_class(core.AgnosticCommandCursor)
AsyncIOMotorLatentCommandCursor = create_asyncio_class(core.AgnosticLatentCommandCursor)
AsyncIOMotorChangeStream = create_asyncio_class(core.AgnosticChangeStream)
AsyncIOMotorGridFSBucket = create_asyncio_class(motor_gridfs.AgnosticGridFSBucket)
AsyncIOMotorGridIn = create_asyncio_class(motor_gridfs.AgnosticGridIn)
AsyncIOMotorGridOut = create_asyncio_class(motor_gridfs.AgnosticGridOut)
AsyncIOMotorGridOutCursor = create_asyncio_class(motor_gridfs.AgnosticGridOutCursor)
AsyncIOMotorClientEncryption = create_asyncio_class(core.AgnosticClientEncryption)
